[pytest]
testpaths = tests
python_files = test_*.py *_test.py
pythonpath = .
addopts = -ra --alluredir=reports/allure-results

markers =
    ui: mark test as UI test
    slow: mark test as slow
    skip_on_captcha: skip test if captcha appears

# Чтобы можно было запускать только UI-тесты
# Пример: pytest -m ui