name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Poetry
      - name: Install Poetry
        run: pip install poetry

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      # 4. Dependencies
      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      # 5. Playwright browsers
      - name: Install Playwright browsers
        run: poetry run playwright install --with-deps

      # 6. Reports dirs
      - name: Create reports dirs
        run: mkdir -p reports/allure-results reports

      # 7. Run tests
      - name: Run tests (API + Playwright)
        run: |
          poetry run pytest tests/playwright tests/api \
            --junitxml=reports/junit.xml

      # 8. Install Allure CLI (СТАБИЛЬНЫЙ источник)
      - name: Install Allure CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre

          curl -L -o allure.tgz \
            https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.27.0/allure-commandline-2.27.0.tgz

          tar -xzf allure.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      # 9. Generate Allure HTML report
      - name: Generate Allure report
        run: |
          allure generate reports/allure-results \
            -o reports/allure-report --clean

      # 10. Upload Allure HTML
      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: reports/allure-report

      # 11. Upload raw Allure results
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: reports/allure-results

      # 12. Upload JUnit
      - name: Upload JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit.xml
